import React, { useState } from 'react';
import api from '../utils/api';
import { ShieldCheck, Smartphone, CheckCircle } from 'lucide-react';

const MfaSetup = () => {
  const [setupData, setSetupData] = useState(null);
  const [token, setToken] = useState('');
  const [message, setMessage] = useState('');

  const handleEnableMfa = async () => {
    try {
      const res = await api.post('/auth/mfa/setup');
      setSetupData(res.data.data || res.data);
    } catch (err) {
      setMessage('Failed to initiate MFA setup.');
    }
  };

  const handleVerify = async (e) => {
    e.preventDefault();
    try {
      // Step 1: Enable MFA (this verifies the token AND enables it)
      await api.post('/auth/mfa/enable', { mfaToken: token });
      setMessage('MFA berhasil diaktifkan! Akun Anda sekarang dilindungi oleh Autentikasi Dua Langkah.');
      setSetupData(null);
    } catch (err) {
      setMessage('Token tidak valid. Pastikan kode 6 digit dari aplikasi Authenticator Anda benar.');
    }
  };

  return (
    <div className="p-8 max-w-3xl mx-auto">
      <div className="flex items-center gap-3 mb-8">
        <ShieldCheck className="w-8 h-8 text-blue-600" />
        <h1 className="text-2xl font-bold text-slate-800">Multi-Factor Authentication (MFA) Setup</h1>
      </div>

      <div className="bg-white rounded-xl shadow-sm border border-slate-200 p-8">
        {message && (
          <div className="mb-6 p-4 bg-slate-100 text-slate-800 rounded-lg flex items-center gap-2">
            <CheckCircle className="text-green-500 w-5 h-5"/>
            {message}
          </div>
        )}

        {!setupData ? (
          <div className="text-center py-8">
            <Smartphone className="w-16 h-16 text-slate-400 mx-auto mb-4" />
            <h2 className="text-xl font-bold text-slate-800 mb-2">Secure Your Account</h2>
            <p className="text-slate-600 mb-6">Add an extra layer of security to your account by enabling Multi-Factor Authentication.</p>
            <button 
              onClick={handleEnableMfa}
              className="bg-blue-600 hover:bg-blue-700 text-white font-bold py-2.5 px-6 rounded-lg transition"
            >
              Setup Authenticator App
            </button>
          </div>
        ) : (
          <div className="space-y-6">
            <div className="flex flex-col md:flex-row gap-8 items-center">
              <div className="bg-white p-4 border border-slate-200 rounded-xl shadow-sm">
                <img src={setupData.qrcode} alt="QR Code" className="w-48 h-48" />
              </div>
              <div className="flex-1 space-y-4">
                <h3 className="text-lg font-bold text-slate-800">Step 1: Scan QR Code</h3>
                <p className="text-slate-600 text-sm">Open Google Authenticator, Authy, or your preferred authenticator app and scan the QR code.</p>
                <div className="pt-2">
                  <span className="text-xs text-slate-500 uppercase font-semibold">Or enter manual key:</span>
                  <div className="mt-1 font-mono text-sm bg-slate-100 p-2 rounded border border-slate-200 break-all">
                    {setupData.secret}
                  </div>
                </div>
              </div>
            </div>

            <hr className="border-slate-100" />

            <div className="space-y-4">
              <h3 className="text-lg font-bold text-slate-800">Step 2: Verify Code</h3>
              <p className="text-slate-600 text-sm">Enter the 6-digit code generated by your authenticator app to confirm setup.</p>
              
              <form onSubmit={handleVerify} className="flex gap-4">
                <input 
                  type="text" 
                  value={token} 
                  onChange={(e) => setToken(e.target.value)}
                  placeholder="000000" 
                  className="flex-1 max-w-xs p-3 text-lg tracking-widest font-mono border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500 outline-none"
                  maxLength="6"
                  required
                />
                <button type="submit" className="bg-slate-900 hover:bg-slate-800 text-white font-bold py-3 px-6 rounded-lg transition">
                  Verify & Enable
                </button>
              </form>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default MfaSetup;
